<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good) Exercises</span></div>

**Exercise 1**

|Term       |Brief description                                                  |
|:----------|:------------------------------------------------------------------|
|Subsetting |selecting a subset of the data in a list or array                  |
|Indexing   |accessing a specific element in a sequence using its index number  |
|Slicing    |selecting a range of elements in a list or array                   |
|Masking    |selecting a elements based on its content                          |

**Exercise 2**

In [8]:
import numpy as np
np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])

np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                         [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                         [10, "J"], [9, "I"]])

numbers = np_array_2d[:, 0].astype(int)
mask = numbers % 2 == 1
result = np_array_2d[mask, 1]
print(result)


['A' 'C' 'E' 'G' 'I']


**Exercise 3**

In [12]:
np_array = np.array([[66, 50, 57, -1, -1],
                [92, -1, 88, -1, -1],
                [75, -1, -1, 76, -1],
                [-1, 51, 87, -1, -1],
                [71, -1, 67, -1, 69]])

np_array[np_array < 50] = -1  # Values below 50 become -1
np_array[np_array > 50] = 1   # Values above 50 become 1
np_array[np_array == 50] = 0  # Values equal to 50 become 0

# Print the final array
print(np_array)


[[ 1  0  1 -1 -1]
 [ 1 -1  1 -1 -1]
 [ 1 -1 -1  1 -1]
 [-1  1  1 -1 -1]
 [ 1 -1  1 -1  1]]
